1. 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy, short for Numerical Python, is a foundational library in Python that greatly enhances Python’s capabilities in scientific computing and data analysis. Its purpose is to provide a powerful array-processing package that efficiently handles large datasets, allowing users to perform numerical operations quickly and effectively. Here’s a breakdown of how and why it’s so valuable:

In [ ]:
Purpose of NumPy

In [ ]:
1) Efficient Array Operations: NumPy introduces the ndarray (N-dimensional array), which can represent large, multi-dimensional arrays and matrices.
   This object allows for fast and space-efficient operations on large datasets, which is ideal for scientific and numerical computations.

2) Mathematical and Statistical Functions: It includes a comprehensive collection of mathematical functions for linear algebra, Fourier transforms,
   and random number generation, making it well-suited for scientific tasks.

3) Integration with Other Libraries: Many other scientific libraries, such as SciPy, pandas, and scikit-learn, build on or integrate with NumPy, making it an essential component in the broader Python ecosystem for data science.


In [ ]:
Advantages of NumPy in Scientific Computing and Data Analysis

In [ ]:
1) Performance: NumPy's operations are implemented in C and Fortran, which makes it much faster than Python’s built-in lists for large datasets.
It allows vectorized operations, which means operations are performed on entire arrays rather than individual elements, greatly enhancing speed.

2) Memory Efficiency: The ndarray structure uses less memory than standard Python lists. It stores data in contiguous memory blocks,
   which reduces memory usage and enables faster access.

3) Broadcasting: NumPy’s broadcasting allows operations on arrays of different shapes and sizes without requiring the explicit replication of data,
   saving both time and memory.

4) Interoperability: NumPy arrays can be used in conjunction with other data science libraries and data formats, such as CSV, HDF5,
   and even integration with other languages like R, C, and Fortran.


In [ ]:
How NumPy Enhances Python’s Capabilities

In [ ]:
1) Vectorized Operations: By applying operations to entire arrays or subarrays, NumPy avoids slow Python loops, making numerical computations much faster.

2) Mathematical Efficiency: Operations like element-wise addition, subtraction, multiplication,
   and more complex operations (e.g., dot products, cross products) are optimized for high performance in NumPy.

3) Data Manipulation and Reshaping: With functions like reshape(), transpose(), and concatenate(), NumPy makes it easy to manipulate and transform
   data structures as needed.


In [ ]:
Overall, NumPy transforms Python into a highly efficient, versatile tool for numerical analysis and data manipulation, offering speed, memory efficiency,
and a comprehensive set of functionalities that are essential in scientific computing.

2. 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?


In NumPy, both np.mean() and np.average() compute the average of array elements, but they have a few key differences, especially when handling weights.

In [ ]:
np.mean()

In [ ]:
1) Purpose: Computes the arithmetic mean (average) of array elements along a specified axis.

2) Syntax: np.mean(array, axis=None).

3) Functionality: Simple mean; does not support weights.

4) Use Case: When you need the straightforward arithmetic mean without any weights.

In [ ]:
np.average()

1) Purpose: Computes the weighted average of array elements along a specified axis.

2) Syntax: np.average(array, axis=None, weights=None).

3) Functionality: Allows for weights, where each element can contribute differently to the final average based on its associated weight.

4) Use Case: When you want a weighted average. If weights=None, it behaves like np.mean().


In [ ]:
Key Differences and When to Use Each

1) Weights: Use np.average() when you need to account for weights; otherwise, np.mean() is sufficient.

2) Syntax simplicity: np.mean() has a simpler syntax, making it easier to use for basic averages.

In [ ]:
In summary:

1) Use np.mean() for unweighted means.

2) Use np.average() when you need weighted means, or where you may need flexibility to add weights later.

3. 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays?

In NumPy, reversing an array can be done using slicing, the flip() function, and other methods, each offering flexibility for reversing along different axes. Here’s a breakdown of the primary techniques, with examples for both 1D and 2D arrays.

In [ ]:
1. 1. Reversing a 1D Array

In [ ]:
Method 1: Using Slicing ([::-1])

In a 1D array, you can reverse all elements by slicing with a step of -1.


In [ ]:
import numpy as np

# 1D Array
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print("Original 1D Array:", arr_1d)
print("Reversed 1D Array (slicing):", reversed_arr_1d)

In [ ]:
2. Method 2: Using np.flip()

In [ ]:
The np.flip() function can also reverse the elements in a 1D array.

In [ ]:
reversed_arr_1d_flip = np.flip(arr_1d)
print("Reversed 1D Array (np.flip):", reversed_arr_1d_flip)

In [ ]:
2. Reversing a 2D Array

In [ ]:
In a 2D array, you can reverse along different axes:

1) Axis 0: Reverse along rows (up-down)

2) Axis 1: Reverse along columns (left-right)

3) Both Axes: Reverse both rows and columns (diagonal flip)


In [ ]:
Method 1: Using Slicing

In [ ]:
1. Reverse Rows (axis 0):

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]
print("Original 2D Array:\n", arr_2d)
print("Reversed Rows:\n", reversed_rows)

In [ ]:
2. Reverse Columns (axis 1):

In [ ]:
reversed_cols = arr_2d[:, ::-1]
print("Reversed Columns:\n", reversed_cols)

In [ ]:
3. Reverse Both Rows and Columns:

In [ ]:
reversed_both = arr_2d[::-1, ::-1]
print("Reversed Rows and Columns:\n", reversed_both)

In [ ]:
Method 2: Using np.flip()

In [ ]:
The np.flip() function can reverse a 2D array along a specified axis or both axes.

Reverse Rows (axis 0):


In [ ]:
reversed_rows_flip = np.flip(arr_2d, axis=0)
print("Reversed Rows (np.flip):\n", reversed_rows_flip)

In [ ]:
2. Reverse Columns (axis 1):

python
Copy code
reversed_cols_flip = np.flip(arr_2d, axis=1)
print("Reversed Columns (np.flip):\n", reversed_cols_flip)


In [ ]:
3. Reverse Both Rows and Columns:

python
Copy code
reversed_both_flip = np.flip(arr_2d)
print("Reversed Rows and Columns (np.flip):\n", reversed_both_flip)


In [ ]:
Summary
Method	      Reversing along axis 0	      Reversing along axis 1	         Reversing along both axes
Slicing	      arr[::-1, :]	                arr[:, ::-1]	                    arr[::-1, ::-1]
np.flip()     np.flip(arr, axis=0)	        np.flip(arr, axis=1)	            np.flip(arr)


In [ ]:
These methods give a straightforward way to reverse a NumPy array along any chosen axis or both at once.


4. 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance?

To determine the data type of elements in a NumPy array, you can use the .dtype attribute of the array. For example, if you have a NumPy array called arr, you can find the data type of its elements by checking arr.dtype. This will return a dtype object that represents the type of the elements in the array, such as int32, float64, etc.

In [ ]:
Example:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype)  # Output: int32

In [ ]:
Importance of Data Types in Memory Management and Performance

The data type of elements in a NumPy array is crucial for both memory efficiency and computational performance. Here’s why:

In [ ]:
1. Memory Management:

In [ ]:
1) Each data type requires a specific amount of memory. For example, int32 uses 4 bytes, while int64 uses 8 bytes.
   Using an appropriate data type minimizes memory usage, especially for large arrays.

2) Choosing a smaller data type (like float32 over float64) can save significant memory when dealing with large datasets, which is essential
   when working on systems with limited memory resources.


In [ ]:
2. Performance:

In [ ]:
1) NumPy operations are highly optimized for specific data types. For example, using float32 for floating-point calculations
   can lead to faster execution compared to float64 due to lower memory bandwidth and fewer CPU cycles per element.

2) Data types also affect vectorized operations. Using a consistent and optimal data type allows for faster computations because NumPy can leverage
   low-level optimizations based on data type.


In [ ]:
Choosing the right data type for a NumPy array enables you to balance memory usage and processing speed effectively,
leading to better performance and optimized resource management.


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, an ndarray (n-dimensional array) is a powerful, multi-dimensional array object designed for efficient scientific computing. An ndarray can represent data of the same type, organized across multiple dimensions (axes). Here’s a breakdown of its key features and how it compares to standard Python lists:

In [ ]:
Key Features of ndarray in NumPy

In [ ]:
1) Homogeneous Data: All elements in an ndarray have the same data type, which allows for efficient memory storage and computation.

2) Multi-dimensional: ndarray can have any number of dimensions, such as 1D, 2D, 3D, etc., supporting complex data structures like matrices and tensors.

3) Optimized for Performance: NumPy arrays are implemented in C, providing faster computations than Python lists.
   Operations on ndarrays leverage SIMD (Single Instruction, Multiple Data) and parallelism, optimizing mathematical computations.

4) Element-wise Operations: NumPy supports vectorized operations, allowing operations to be applied to all elements without explicit looping,
   which is faster and more efficient.

5) Memory Efficiency: ndarrays consume less memory than Python lists, especially when handling large datasets, because they store data in contiguous blocks.

6) Broadcasting: NumPy can perform operations on arrays of different shapes without needing to duplicate data, which saves memory and computation time.


In [ ]:
Differences Between ndarrays and Standard Python Lists

Feature	                              ndarray	                                    Python List
Data Type	                         Homogeneous	                                  Heterogeneous
Dimensions            	    Multi-dimensional (n-dimensional)	                Primarily 1D (lists of lists for higher dims)
Memory Efficiency	                   Higher	                                        Lower
Performance	                 Optimized (C-based, vectorized)	                  Slower, especially with loops
Element-wise Operations 	     Supported (vectorized)	                           Not supported (need loops)
Broadcasting	                     Supported	                                     Not available


In [ ]:
 In summary, ndarrays are highly optimized, flexible, and memory-efficient structures, ideal for large-scale numerical and scientific computations,
 whereas Python lists are more general-purpose and not optimized for numerical operations.


6. 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations?

NumPy arrays offer substantial performance benefits over Python lists for large-scale numerical operations due to the following reasons:

In [ ]:
1)  Memory Efficiency: NumPy arrays use contiguous blocks of memory and are of a fixed data type, which allows for more efficient memory usage.
    In contrast, Python lists store pointers to individual objects, which leads to higher memory consumption.
    This contiguous memory layout in NumPy arrays also allows for better cache utilization.

2)  Vectorized Operations: NumPy supports vectorized operations, allowing you to perform element-wise computations without explicit loops.
    These vectorized operations are executed at the compiled, lower level (using optimized C, C++, or Fortran code under the hood),
    avoiding the overhead of Python's interpreter loop and making operations much faster.

3) Broadcasting: NumPy arrays support broadcasting, which allows operations on arrays of different shapes and sizes
   without the need to manually reshape or expand data. This reduces the need for looping and helps in reducing the code complexity and execution time.

4) Low-Level Implementation: NumPy is implemented in C, enabling efficient, low-level operations. This results in much faster execution for numerical tasks
   compared to Python lists, where each operation incurs significant overhead due to Python’s object-oriented architecture.

5) Efficient Math Functions: NumPy offers a wide range of mathematical functions that are optimized for array operations.
   Using these optimized functions is faster than writing custom mathematical operations with Python lists, especially for large datasets.

6) Multidimensional Support: NumPy supports multidimensional arrays and matrices, which simplifies the handling of higher-dimensional data.
   This reduces the need for complex nested lists in Python, making code both faster and more readable.



In [ ]:
Example Benchmark:

1) For large datasets, a simple operation like element-wise addition is typically 10-100x faster with NumPy arrays than with Python lists due to the factors
   above.

2) In summary, NumPy arrays are much more efficient for large-scale numerical computations because they allow optimized, low-level operations, use less memory
   and support faster, vectorized calculations, all of which improve performance significantly.


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output?

In NumPy, the vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively. They allow for the efficient combination of arrays along different axes. Let’s go over each function in detail with examples.

In [ ]:
1. vstack()

Definition: The vstack() function stacks arrays vertically, row by row. It takes a sequence of arrays as input and stacks them along the first axis (axis=0).

Requirements: The input arrays should have the same number of columns (same second dimension size).

In [ ]:
Example of vstack()

In [ ]:
import numpy as np

# Define two 2x2 arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Stack arrays vertically
result_vstack = np.vstack((array1, array2))
print("Result of vstack:\n", result_vstack)

In [ ]:
Output:

In [ ]:
Result of vstack:
 [[1 2]
  [3 4]
  [5 6]
  [7 8]]

In [ ]:
In this example, vstack() stacks array1 and array2 vertically, adding the rows of array2 below the rows of array1.

In [ ]:
2. hstack()

1) Definition: The hstack() function stacks arrays horizontally, column by column. It takes a sequence of arrays as input and stacks
   them along the second axis (axis=1).

2) Requirements: The input arrays should have the same number of rows (same first dimension size).


In [ ]:
Example of hstack()

python

# Define two 2x2 arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Stack arrays horizontally
result_hstack = np.hstack((array1, array2))
print("Result of hstack:\n", result_hstack)


In [ ]:
Output:

In [ ]:
Result of hstack:
 [[1 2 5 6]
  [3 4 7 8]]

In [ ]:
In this example, hstack() stacks array1 and array2 horizontally, appending the columns of array2 to the columns of array1.

In [ ]:
Summary of Key Differences

 Function	                Stacks Along	             Requirement	                     Example Output
vstack()	                Vertical	                Same number of columns	           Rows stacked vertically
hstack()	                Horizontal	              Same number of rows	Columns s      tacked horizontally


In [ ]:
Both functions are useful for reshaping or combining arrays, depending on whether you want them to be added along rows or columns.

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions?



In NumPy, the fliplr() and flipud() methods are used to reverse the order of elements in a given array, but they operate along different dimensions:

In [ ]:
1. np.fliplr() (Flip Left to Right):

1) fliplr() flips the elements in an array horizontally, reversing the order along the second axis (columns).

2) It only works on 2D arrays or higher. For example, in a 2D array, it will reverse the order of columns,
  turning the leftmost column into the rightmost one and vice versa.

3) Example: Given a 2D array [[1, 2, 3], [4, 5, 6]], fliplr() will return [[3, 2, 1], [6, 5, 4]].


In [ ]:
2. np.flipud() (Flip Up to Down):

1) flipud() flips the elements in an array vertically, reversing the order along the first axis (rows).

2) This function works on arrays of any dimension, reversing the order of rows in a 2D array.

3) Example: Given a 2D array [[1, 2, 3], [4, 5, 6]], flipud() will return [[4, 5, 6], [1, 2, 3]].


In [ ]:
Summary of Differences:

1) Axes of Operation: fliplr() reverses columns (axis 1), while flipud() reverses rows (axis 0).

2) Dimensional Requirements: fliplr() requires a 2D array or higher, but flipud() works on arrays of any dimension.


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The numpy.array_split() method is used to divide an array into multiple sub-arrays. This function is especially useful when you need to split an array into a specific number of sections, even if the sections do not divide the array evenly.



In [ ]:
Key Points of array_split()
1. Parameters:

1) The first parameter is the array you want to split.

2) The second parameter specifies the number of sections you want to split the array into.

2. Uneven Splits:

1) If the array cannot be divided evenly, array_split() handles this by creating some sub-arrays with more elements than others.

2) The first few sections will have one extra element to make up for any uneven split.

3) For example, if you split an array with 10 elements into 3 parts, array_split() will create three sub-arrays with 4, 3, and 3 elements, respectively.


In [ ]:
Example

In [ ]:
import numpy as np

# Array of 10 elements
arr = np.arange(10)

# Split into 3 parts
split_arr = np.array_split(arr, 3)
print(split_arr)

In [ ]:
Output
scss

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
In this example, the array is split into three parts. The first sub-array has 4 elements, while the other two have 3 elements each.

In [ ]:
Summary

array_split() is useful for handling uneven splits because it intelligently distributes the extra elements across the first few sub-arrays,
ensuring that every section gets as close to an even number of elements as possible.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In NumPy, vectorization and broadcasting are techniques that enable efficient array operations by eliminating the need for explicit loops, thus leveraging the power of low-level, optimized C code under the hood.

In [ ]:
Vectorization

Vectorization in NumPy refers to the practice of replacing explicit loops with array expressions to perform element-wise operations directly on arrays.
Instead of iterating through each element individually,
vectorized operations allow you to apply functions or arithmetic operations to entire arrays simultaneously.


In [ ]:
For example:

In [ ]:
import numpy as np

# Without vectorization
arr = np.array([1, 2, 3, 4])
result = np.zeros_like(arr)
for i in range(len(arr)):
    result[i] = arr[i] * 2

# With vectorization
result = arr * 2

In [ ]:
 1) Vectorization significantly improves performance because it uses compiled code in the background, which is faster
    than running Python loops.

2)  Broadcasting
    Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller
    array along the dimensions of the larger array. It matches shapes by "stretching" or "broadcasting" dimensions without making copies of the data,
    which saves both time and memory.



In [ ]:
For example:

In [ ]:
a = np.array([1, 2, 3])  # Shape (3,)
b = np.array([[10], [20], [30]])  # Shape (3, 1)

# Broadcasting b to match the shape of a for element-wise addition
result = a + b

In [ ]:
Here, a (shape (3,)) is "broadcast" across b (shape (3, 1)) so that element-wise addition can occur without reshaping or creating redundant copies.

Contribution to Efficiency

1) Memory Efficiency: Broadcasting avoids unnecessary memory allocation by not creating copies of arrays for matching shapes.

2) Speed: Vectorized operations eliminate Python loops, allowing operations to run in optimized C code.

3) Readability: Using vectorization and broadcasting results in cleaner, more readable code, as complex loops are replaced by concise array operations.


In [ ]:
Together, vectorization and broadcasting make NumPy highly efficient for numerical computing tasks, particularly on large datasets, by reducing computation time and memory usage.


Practical Questions:

11. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns?

Here’s the 3x3 NumPy array with random integers between 1 and 100:

In [ ]:
Original Array:

lua

[[36, 87, 95],
 [98, 73,  4],
 [23, 76, 46]]

In [ ]:
After interchanging its rows and columns (transpose):

In [ ]:
[[36, 98, 23],
 [87, 73, 76],
 [95,  4, 46]]

12. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array?

import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

array_1d, array_2x5, array_5x2

In [ ]:
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))


In [ ]:
Here are the results of the operations you requested:

1. 1D NumPy array with 10 elements:

[0,1,2,3,4,5,6,7,8,9]

2. Reshaped into a 2x5 array:

[ 0 1 2 3 4
  5 6 7 8 9)

3. Reshaped into a 5x2 array:

  \begin{bmatrix} 0 & 1 \\ 2 & 3 \\ 4 & 5 \\ 6 & 7 \\ 8 & 9 \end{bmatrix} \] &#8203;:contentReference[oaicite:0]{index=0}&#8203;


13. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array?

In [ ]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array to make it 6x6
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

array_6x6


In [ ]:
Result
array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.39671065, 0.3827843 , 0.89790838, 0.44861613,
        0.        ],
       [0.        , 0.21743875, 0.8099038 , 0.21051365, 0.45988436,
        0.        ],
       [0.        , 0.21039723, 0.39052158, 0.89738868, 0.71447211,
        0.        ],
       [0.        , 0.33356364, 0.38303098, 0.44530941, 0.82408258,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])


In [ ]:
Here is the resulting 6x6 array with random float values in the center and a border of zeros:

\begin{bmatrix} 0 & 0 & 0 & 0 & 0 & 0 \\ 0 & 0.3967 & 0.3828 & 0.8979 & 0.4486 & 0 \\ 0 & 0.2174 & 0.8099 & 0.2105 & 0.4599 & 0 \\ 0 & 0.2104 & 0.3905 &
 0.8974 & 0.7145 & 0 \\ 0 & 0.3336 & 0.3830 & 0.4453 & 0.8241 & 0 \\ 0 & 0 & 0 & 0 & 0 & 0 \\ \end{bmatrix} \]
 &#8203;:contentReference[oaicite:0]{index=0}&#8203;

14. Using NumPy, create an array of integers from 10 to 60 with a step of 5?



In [ ]:
import numpy as np

# Creating an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
array

In [ ]:
Result
array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [ ]:
The array of integers from 10 to 60 with a step of 5 is:

In [ ]:
[10 15 20 25 30 35 40 45 50 55 60]

15. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element?



In [ ]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_arr = np.char.upper(arr)      # Uppercase transformation
lowercase_arr = np.char.lower(arr)      # Lowercase transformation
titlecase_arr = np.char.title(arr)      # Title case transformation
capitalize_arr = np.char.capitalize(arr) # Capitalize transformation (first letter)

uppercase_arr, lowercase_arr, titlecase_arr, capitalize_arr


In [ ]:
Result
(array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6'),
 array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'))

In [ ]:
Here are the results of applying different case transformations to each element in the NumPy array:

Uppercase: ['PYTHON', 'NUMPY', 'PANDAS']
Lowercase: ['python', 'numpy', 'pandas']
Title case: ['Python', 'Numpy', 'Pandas']
Capitalized (first letter uppercase, rest lowercase): ['Python', 'Numpy', 'Pandas'] ​​

16. Generate a NumPy array of words. Insert a space between each character of every word in the array?



In [ ]:
To generate a NumPy array of words and insert a space between each character in every word, we can use the following approach:

Create a NumPy array of words.
Apply a function to each word that adds a space between its characters.

In [ ]:
import numpy as np

# Step 1: Create a NumPy array of words
words = np.array(["hello", "world", "numpy", "array"])

# Step 2: Add a space between each character in every word
spaced_words = np.array([" ".join(word) for word in words])

# Output the result
spaced_words


In [ ]:
This will result in a NumPy array where each word has a space between each character:

In [ ]:
array(['h e l l o', 'w o r l d', 'n u m p y', 'a r r a y'], dtype='<U9')

17. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division?

In [ ]:
import numpy as np

# Creating two 2D NumPy arrays
array1 = np.array([[5, 10, 15], [20, 25, 30]])
array2 = np.array([[2, 4, 6], [8, 10, 12]])

# Element-wise operations
addition = np.add(array1, array2)
subtraction = np.subtract(array1, array2)
multiplication = np.multiply(array1, array2)
division = np.divide(array1, array2)

addition, subtraction, multiplication, division


In [ ]:
It seems like I can’t do more advanced data analysis right now. Please try again later. If you'd like, I can guide you through how to perform these operations
 on your own system. Let me know if you'd like instructions! ​​


18. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements?



In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract its diagonal elements
diagonal_elements = np.diag(identity_matrix)
identity_matrix, diagonal_elements


19. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array?



In [ ]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, 100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]
prime_numbers


20. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly  averages?



In [ ]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# Generating random temperatures between a plausible range (e.g., 15 to 30 degrees Celsius)
np.random.seed(0)  # For reproducibility
daily_temperatures = np.random.randint(15, 31, size=30)

# Reshape to 4 weeks (7 days each) and calculate weekly averages
weekly_temperatures = daily_temperatures.reshape(4, 7)
weekly_averages = weekly_temperatures.mean(axis=1)

daily_temperatures, weekly_averages